// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url:
      process.env["DATABASE_URL"] ??
      process.env["POSTGRES_PRISMA_URL"] ??
      process.env["POSTGRES_URL"] ??
      // Fallback to satisfy Prisma CLI config validation during builds.
      // Runtime DB access still requires a real connection string.
      "postgresql://localhost:5432/postgres",
  },
});
